/*
 * This file was automatically generated by EvoSuite
 * Mon May 02 11:08:57 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution_266_ESTest extends Solution_266_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution_266 solution_266_0 = new Solution_266();
      HashMap<Character, Integer> hashMap0 = new HashMap<Character, Integer>();
      solution_266_0.ori = (Map<Character, Integer>) hashMap0;
      Character character0 = Character.valueOf('d');
      Integer integer0 = new Integer((-1426));
      hashMap0.put(character0, integer0);
      // Undeclared exception!
      try { 
        solution_266_0.minWindow("p+HZ%<1!%H*", "");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution_266 solution_266_0 = new Solution_266();
      // Undeclared exception!
      try { 
        solution_266_0.minWindow("k|Y", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Solution_266", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution_266 solution_266_0 = new Solution_266();
      solution_266_0.ori = null;
      // Undeclared exception!
      try { 
        solution_266_0.check();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Solution_266", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution_266 solution_266_0 = new Solution_266();
      solution_266_0.minWindow("", "T)+~3p#] tr{Xln");
      solution_266_0.minWindow("T)+~3p#] tr{Xln", "");
      boolean boolean0 = solution_266_0.check();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution_266 solution_266_0 = new Solution_266();
      boolean boolean0 = solution_266_0.check();
      assertTrue(boolean0);
  }
}
